apiVersion: v1
kind: PersistentVolume
metadata:
  name: chartmuseum-pv
  namespace: chartmuseum
  labels:
    name: chartmuseum-pv
spec:
  capacity:
   storage: 2Gi
  volumeMode: Filesystem
  accessModes:
   - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/chartmuseum # Path to the directory this PV refers to.
  nodeAffinity: # nodeAffinity is required when using local volumes.
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s2
          - k8s3