apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ac-chartmuseum
  namespace: chartmuseum
spec:
  interval: 5m
  chart:
    spec:
      chart: chartmuseum
      version: "3.6.2"
      sourceRef:
        kind: HelmRepository
        name: chartmuseum
        namespace: flux-system
      interval: 1m
  values:
    env:
      open:
        STORAGE: local
        DISABLE_API: false
    persistence:
      enabled: true
      path: /mnt/chartmuseum
      existingClaim: chartmuseum-pvc
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - name: chartmuseum.io
          path: /
      