# This is a basic workflow to help you get started with Actions

name: PR merge

# Controls when the workflow will run
on:
  pull_request:
   branches: [main]
   types: [closed]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
        token: ${{ secrets.GH_TOKEN }}
    - name: Install dependencies
      run: |
        sudo wget -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.6.3/yq_linux_amd64
        sudo chmod +x /usr/local/bin/yq
        sudo curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        sudo chmod +x get_helm.sh
        ./get_helm.sh
    - name: Build & deploy monorepo
      id: build_and_deploy
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        ACTION: deploy
      shell: bash
      run: |
          chmod +x ./semver.sh
          chmod +x ./build.sh
          ./build.sh
    - name: test outputs
      shell: bash
      run: |
        STR=${{join(steps.build_and_deploy.outputs.*, ',')}}
        echo $STR
        for str in ${STR//,/ } ; do \
          echo "+ \"$str\"" \
        done \


