# This is a basic workflow to help you get started with Actions

name: PR review

# Controls when the workflow will run
on:
  pull_request_review:
   types: [submitted]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
        token: ${{ secrets.GH_TOKEN }}
    - name: Build monorepo
      env:
        ACTION: build
      shell: bash
      run: |
          chmod +x ./build.sh
          ./build.sh